### ISSUE TITLE
yarn build: Failed to minify the code from this file

### ISSUE THREAD

**Issue by formreact** [WhatAKitty/react-script-antd-pro#3]
yarn build时：

Failed to minify the code from this file:

        ./node_modules/react-fetch-mock/src/index.js:4

得注释掉index.js里的：
//import FetchMock from 'react-fetch-mock';

//window.fetch = new FetchMock(require('./__mocks__')).fetch;
才能正常build。

**Comment by WhatAKitty** [comment]
升级下`react-fetch-mock`即可。
`yarn add react-fetch-mock`
